/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_n1_dtvhal_DtvHalService */

#ifndef _Included_com_example_n1_dtvhal_DtvHalService
#define _Included_com_example_n1_dtvhal_DtvHalService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_n1_dtvhal_DtvHalService
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT jint JNICALL Java_com_example_n1_dtvhal_DtvHalService_init
  (JNIEnv *, jobject);

/*
 * Class:     com_example_n1_dtvhal_DtvHalService
 * Method:    switch_to
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_n1_dtvhal_DtvHalService_switch_1to
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_n1_dtvhal_DtvHalService
 * Method:    power_control
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_n1_dtvhal_DtvHalService_power_1control
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
